# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-25 19:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hex_value', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('color', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.Color')),
            ],
        ),
    ]
