# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-25 20:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_color_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='label',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.Label'),
        ),
    ]
